### ISSUE TITLE
Output streams are empty

### ISSUE THREAD

**Issue by JamesMGreene** [nicoFuccella/pdf-thumbnail#2]
I can't get any of the output streams (or resulting JPG files), even from your own `test/` directory, to be anything other than empty (or 0-byte files).

OS: Mac OSX Mojave
Node version: `10.13.0`
ImageMagick version: `7.0.8-23` (installed via `brew`)

Any suggestions?

**Comment by nicofuccella** [comment]
@JamesMGreene you probably don't have installed ghostscript. I forgot to include that info in README.md. I've updated README.md with this info in v1.0.6

**Comment by JamesMGreene** [comment]
That did the trick! Thank you. 👌
