### ISSUE TITLE
The generated thumbnail is empty (0 bytes)

### ISSUE THREAD

**Issue by scozma** [nicoFuccella/pdf-thumbnail#3]
Hi, 

I am trying to create a PNG thumbnail from a PDF file, but the generated file is empty (an image with 0 bytes size). I am using an example provided by the documentation. Here is my code:

```
const http = require('http');
const fs = require('fs');
const pdf = require('pdf-thumbnail');

const filePath = 'test.pdf';
const resizePath = 'myImg-thumb.png';

http.createServer(function (req, res) {

	//with stream
	pdf(fs.createReadStream(filePath))
	.then(data /*is a stream*/ => data.pipe(fs.createWriteStream(resizePath)))
	.catch(err => console.error(err))

}).listen(3000);

console.log('Server running.');
```
Can you please help? Thanks!

**Comment by scozma** [comment]
Sorry, I just saw there was another issue opened (now closed) related to this issue and I installed `ghostscript` but I still get a 0 bytes image. I ran:

```
npm i pdf-thumbnail
sudo apt-get install imagemagick
sudo apt-get install ghostscript
```

And everything was installed successfully.

**Comment by nicofuccella** [comment]
Hi @scozma, I tried and your code seems to work. Could you give me more details about the error you get?

**Comment by scozma** [comment]
Hi @nicofuccella - I don't get any error. Everything seems to be fine, but the generated file is empty (0 bytes). Is there a way I can debug this? Thanks for your help!

**Comment by nicofuccella** [comment]
The file I get with exactly your code is fine. Maybe your imagemagick installation cannot communicate with the Ghostscript one. You can try `convert -verbose test.pdf myImg-thumb.png` to verify your installations. Let me know

**Comment by scozma** [comment]
You mean I should run this into the terminal when I am on the project folder?
If so, I did it and I got this error:

```
convert -verbose test.pdf myImg-thumb.png 
convert-im6.q16: not authorized `test.pdf' @ error/constitute.c/ReadImage/412.
convert-im6.q16: no images defined `myImg-thumb.png' @ error/convert.c/ConvertImageCommand/3258.
```

**Comment by scozma** [comment]
@nicofuccella - I managed to make `convert -verbose test.pdf myImg-thumb.png ` work - this converted the entire PDF file into 4 images with transparent background (not so important at this stage).
But the code from my file now creates a PNG image (no longer empty, but of 61.3 kB) which cannot be open as it fails with this error: `Fatal error reading PNG image file: Not a PNG file` and I don't have a general problem with the PNG files because I can open the images generated with the `convert...` command as I explained above.

**Comment by philiplindberg** [comment]
I'm experiencing the same thing @scozma is seeing.

Running `convert -verbose test.pdf myImg-thumb.png` works fine without errors, and the generated .png works fine.

However, when I try to run the following code on my node server, the generated thumbnail is empty: 
```
pdf(fs.readFileSync(filePath))
    .then(data => {
      data.pipe(fs.createWriteStream(thumbnailPath))
    })
    .catch(err => console.log(err))
```

**Comment by Ng2k** [comment]
@philiplindberg is your node server online or not? Maybe you haven't installed ImageMagick or ghostscript on that server, but I need more details about.

**Comment by scozma** [comment]
@philiplindberg @nicofuccella When I ran `convert -verbose test.pdf myImg-thumb.png` for the first time, I got an error, as I mentioned above. Then I fixed it by changing this file: `/etc/ImageMagick-6/policy.xml` as described here: 
https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453
`imageMagick` and `ghostscript` are both installed and the generated file is corrupted (not empty - it has 61.3 kB). 
I hope this helps.

**Comment by philiplindberg** [comment]
@Ng2k Just tested this with a node server running in a VM, and everything works as expected. 

Before I was running node from macOS, which was generating the empty thumbnails but without any errors. Weird...

**Comment by seasiaopensource** [comment]
Hii I got same issue. How to fix that i run into node server in Ubuntu.
successfully able to generate Image from "convert -verbose test.pdf myImg-thumb.png"
But not able do generate by code

**Comment by johnmicroservice** [comment]
I'm dealing with that same issue

**Comment by Ng2k** [comment]
@seasiaopensource @johnmicroservice have you installed `imageMagick` and `ghostscript` on your node server? However I need more infos.

**Comment by ibenilsen** [comment]
@scozma @johnmicroservice 
I discovered the cause of this in my situation was when converting multi-page PDF's. ImageMagick was having trouble communicating with ghostscript due to a bug that has since been fixed (https://bugs.ghostscript.com/show_bug.cgi?id=700315). 

Currently brew is hosting ghostscript@9.2.6. 

If you've installed ghostscript with brew you may need to uninstall and manually install 9.2.7 using the downloads available on their website.

**Comment by nicofuccella** [comment]
@ibenilsen cool. If @johnmicroservice and @seasiaopensource encountered the same bug and resolved just updating ghostscript we should add a note in the readme...
